# Netlify configuration for Clubify.mk

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Next.js runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"
