# Netlify configuration for Clubify.mk

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Ignore this, we're using pnpm

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Prevent Netlify from using npm
[build.processing]
  skip_processing = false
